"""
Django settings for cosap_api project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import json
import os
from pathlib import Path

# import sentry_sdk
# from sentry_sdk.integrations.django import DjangoIntegration
# from sentry_sdk.integrations.logging import ignore_logger

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["COSAP_DJANGO_SECRET"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("COSAP_DJANGO_DEBUG") == "True"

# Add production security settings
if not DEBUG:
    # Security Headers
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # HTTPS settings (if using HTTPS)
    SECURE_SSL_REDIRECT = os.environ.get("SECURE_SSL_REDIRECT", "False") == "True"
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    # Session Security
    SESSION_COOKIE_SECURE = os.environ.get("SESSION_COOKIE_SECURE", "True") == "True"
    CSRF_COOKIE_SECURE = os.environ.get("CSRF_COOKIE_SECURE", "True") == "True"
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SAMESITE = "Lax"

ALLOWED_HOSTS = ["localhost", "web"] + json.loads(
    os.environ.get("COSAP_BIO_HOST", "[]")
)

# Fix CORS settings
CSRF_TRUSTED_ORIGINS = json.loads(os.environ.get("COSAP_CORS_TRUSTED_ORIGINS", "[]"))

CORS_ALLOWED_ORIGINS = json.loads(
    os.environ.get("COSAP_CORS_ALLOWED_ORIGINS", '["http://localhost:3000"]')
)

# Don't allow all credentials in production
CORS_ALLOW_CREDENTIALS = os.environ.get("CORS_ALLOW_CREDENTIALS", "False") == "True"

# Restrict CORS headers
CORS_ALLOW_HEADERS = [
    "authorization",
    "content-type",
    "range",
    "cache-control",
    "upload-length",
    "upload-name",
    "upload-offset",
    "x-csrf-token",
]
CORS_ALLOW_CREDENTIALS = True

# Application definition
INSTALLED_APPS = [
    "api.apps.ApiConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework.authtoken",
    "corsheaders",
    "rest_framework",
    "django_extensions",
    "django_drf_filepond",
    "django_json_widget",
    "django_elasticsearch_dsl",
    "django_prometheus",
]

MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_prometheus.middleware.PrometheusAfterMiddleware",
]

ROOT_URLCONF = "cosap_api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "cosap_api.wsgi.application"

# Add caching for production
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://redis:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
        "KEY_PREFIX": "cosap",
        "TIMEOUT": 300,
    }
}

# Session cache
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "api.authentication.BearerAuthentication",
    ],
}

# Substitute User Model
AUTH_USER_MODEL = "api.CustomUser"

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django_prometheus.db.backends.postgresql",
        "NAME": os.environ.get("COSAP_DB_NAME", "postgres"),
        "USER": os.environ.get("COSAP_DB_USER", "postgres"),
        "PASSWORD": os.environ.get("COSAP_DB_PASSWORD", "postgres"),
        "HOST": "db",
        "PORT": "5432",
        "OPTIONS": {
            "sslmode": "prefer",  # Add SSL preference
        },
        "CONN_MAX_AGE": 600,  # Connection pooling
        "TEST": {
            "NAME": "cosap_test_db",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Stored files

MEDIA_ROOT = "/user_files"
MEDIA_TMP = os.path.join(MEDIA_ROOT, "tmp")
os.makedirs(MEDIA_TMP, exist_ok=True)
MEDIA_URL = "/media/"

DJANGO_DRF_FILEPOND_UPLOAD_TMP = os.path.join(BASE_DIR, "filepond_temp_files")
DJANGO_DRF_FILEPOND_FILE_STORE_PATH = BASE_DIR

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Celery Configuration Options
RABBITMQ_DEFAULT_VHOST = os.getenv("RABBITMQ_DEFAULT_VHOST", "vhost")
RABBITMQ_DEFAULT_USER = os.getenv("RABBITMQ_DEFAULT_USER", "guest")
RABBITMQ_DEFAULT_PASS = os.getenv("RABBITMQ_DEFAULT_PASS", "guest")

CELERY_BROKER_URL = f"amqp://{RABBITMQ_DEFAULT_USER}:{RABBITMQ_DEFAULT_PASS}@rabbitmq:5672/{RABBITMQ_DEFAULT_VHOST}"
CELERY_RESULT_BACKEND = "redis://redis:6379/0"
CELERY_TASK_ROUTES = {
    "parse_project_results": {
        "exchange": "cosap_worker",
        "exchange_type": "direct",
        "routing_key": "cosap_worker",
    },
    "dna_pipeline_task": {
        "exchange": "cosap_worker",
        "exchange_type": "direct",
        "routing_key": "cosap_worker",
    },
    "annotation_task": {
        "exchange": "cosap_worker",
        "exchange_type": "direct",
        "routing_key": "cosap_worker",
    },
    "parse_vcf_task": {
        "exchange": "cosap_worker",
        "exchange_type": "direct",
        "routing_key": "cosap_worker",
    },
}
CELERY_ACCEPT_CONTENT = ["json", "msgpack", "yaml"]


ELASTICSEARCH_DSL = {
    "default": {
        "hosts": "http://elasticsearch:9200",
        "http_auth": ("elastic", os.environ.get("ELASTIC_PASSWORD", "changeme")),
        "timeout": 60,
        "verify_certs": False,
        "connection_class": "elasticsearch.connection.http_urllib3.Urllib3HttpConnection",
    },
}


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "level": "INFO",
        },
        # Remove file handler for production
        # "file": {
        #     "level": "DEBUG",
        #     "class": "logging.FileHandler",
        #     "filename": "log.django",
        # },
    },
    "root": {
        "handlers": ["console"],  # Only console in production
        "level": os.getenv("DJANGO_LOG_LEVEL", "WARNING"),  # Higher log level
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "WARNING"),
        },
        "gunicorn": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

DATA_UPLOAD_MAX_NUMBER_FIELDS = 100000

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.environ.get("EMAIL_HOST", "mailserver")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True") == "True"
EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", "False") == "True"
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "noreply@yourdomain.com")
SUPPORT_EMAIL = os.environ.get("SUPPORT_EMAIL", "support@cosap.bio")
SERVER_EMAIL = os.environ.get("SERVER_EMAIL", DEFAULT_FROM_EMAIL)

ANNOTATE_VARIANTS = os.environ.get("ANNOTATE_VARIANTS", "True") == "True"
